 package com.sun.tools.doclets.formats.html.resources;
 
 import java.util.ListResourceBundle;
 
 public final class standard_pt_BR extends ListResourceBundle
 {
   protected final Object[][] getContents()
   {
     return new Object[][] {
                { "tdoclet.0_Fields_and_Methods", "&quot;{0}&quot; Campos e métodos" },
 				{ "tdoclet.All_Packages", "Todos os pacotes" },
 				{ "tdoclet.Annotation_Type_Hierarchy", "Annotation Type Hierarchy" },
 				{ "tdoclet.Blank", "Em Branco" },
 				{ "tdoclet.CLASSES", "CLASSES" },
 				{ "tdoclet.Cannot_handle_no_packages", "Cannot handle no packages." },
 				{ "tdoclet.ClassUse_Annotation", "Classes in {1} with annotations of type {0}" },
 				{ "tdoclet.ClassUse_Classes.in.0.used.by.1", "Classes in {0} used by {1}" },
 				{ "tdoclet.ClassUse_ConstructorAnnotations", "Constructors in {1} with annotations of type {0}" },
 				{ "tdoclet.ClassUse_ConstructorArgs", "Constructors in {1} with parameters of type {0}" },
 				{ "tdoclet.ClassUse_ConstructorArgsTypeParameters", "Constructor parameters in {1} with type arguments of type {0}" },
 				{ "tdoclet.ClassUse_ConstructorParameterAnnotations", "Constructor parameters in {1} with annotations of type {0}" },
 				{ "tdoclet.ClassUse_ConstructorThrows", "Constructors in {1} that throw {0}" },
 				{ "tdoclet.ClassUse_Field", "Fields in {1} declared as {0}" },
 				{ "tdoclet.ClassUse_FieldAnnotations", "Fields in {1} with annotations of type {0}" },
 				{ "tdoclet.ClassUse_FieldTypeParameter", "Fields in {1} with type parameters of type {0}" },
 				{ "tdoclet.ClassUse_ImplementingClass", "Classes in {1} that implement {0}" },
 				{ "tdoclet.ClassUse_MethodAnnotations", "Methods in {1} with annotations of type {0}" },
 				{ "tdoclet.ClassUse_MethodArgs", "Methods in {1} with parameters of type {0}" },
 				{ "tdoclet.ClassUse_MethodArgsTypeParameters", "Method parameters in {1} with type arguments of type {0}" },
 				{ "tdoclet.ClassUse_MethodParameterAnnotations", "Method parameters in {1} with annotations of type {0}" },
 				{ "tdoclet.ClassUse_MethodReturn", "Methods in {1} that return {0}" },
 				{ "tdoclet.ClassUse_MethodReturnTypeParameter", "Methods in {1} that return types with arguments of type {0}" },
 				{ "tdoclet.ClassUse_MethodThrows", "Methods in {1} that throw {0}" },
 				{ "tdoclet.ClassUse_MethodTypeParameter", "Methods in {1} with type parameters of type {0}" },
 				{ "tdoclet.ClassUse_No.usage.of.0", "No usage of {0}" },
 				{ "tdoclet.ClassUse_PackageAnnotation", "Packages with annotations of type {0}" },
 				{ "tdoclet.ClassUse_Packages.that.use.0", "Packages that use {0}" },
 				{ "tdoclet.ClassUse_Subclass", "Subclasses of {0} in {1}" },
 				{ "tdoclet.ClassUse_Subinterface", "Subinterfaces of {0} in {1}" },
 				{ "tdoclet.ClassUse_Title", "Uses of {0}<br>{1}" },
 				{ "tdoclet.ClassUse_TypeParameter", "Classes in {1} with type parameters of type {0}" },
 				{ "tdoclet.ClassUse_Uses.of.0.in.1", "Uses of {0} in {1}" },
 				{ "tdoclet.Class_Hierarchy", "Hierarquia de classes" },
 				{ "tdoclet.Constructor_for", "Construtor para {0}" },
 				{ "tdoclet.Contents", "Conteúdo" },
 				{ "tdoclet.Deprecated_API", "API depreciada" },
 				{ "tdoclet.Deprecated_Annotation_Type_Members", "Deprecated Annotation Type Elements" },
 				{ "tdoclet.Deprecated_Annotation_Types", "Deprecated Annotation Types" },
 				{ "tdoclet.Deprecated_Classes", "Classes depreciadas" },
 				{ "tdoclet.Deprecated_Constructors", "Construtores depreciados" },
 				{ "tdoclet.Deprecated_Enum_Constants", "Deprecated Enum Constants" },
 				{ "tdoclet.Deprecated_Enums", "Deprecated Enums" },
 				{ "tdoclet.Deprecated_Errors", "Deprecated Errors" },
 				{ "tdoclet.Deprecated_Exceptions", "Deprecated Exceptions" },
 				{ "tdoclet.Deprecated_Fields", "Deprecated Fields" },
 				{ "tdoclet.Deprecated_Interfaces", "Deprecated Interfaces" },
 				{ "tdoclet.Deprecated_List", "Deprecated List" },
 				{ "tdoclet.Deprecated_Methods", "Deprecated Methods" },
 				{ "tdoclet.Description", "Descrição" },
 				{ "tdoclet.Description_From_Class", "Description copied from class: {0}" },
 				{ "tdoclet.Description_From_Interface", "Description copied from interface: {0}" },
 				{ "tdoclet.Detail", "DETALHES:" },
 				{ "tdoclet.Docs_generated_by_Javadoc", "Documentação gerada pelo Javadoc (tradução parcial por Kaléu Caminha)." },
 				{ "tdoclet.Enclosing_Class", "Enclosing class:" },
 				{ "tdoclet.Enclosing_Interface", "Enclosing interface:" },
 				{ "tdoclet.Enum_Hierarchy", "Hierarquia Enum" },
 				{ "tdoclet.Error_in_packagelist", "Error in using -group option: {0} {1}" },
 				{ "tdoclet.FRAMES", "FRAMES" },
 				{ "tdoclet.Factory_Method_Detail", "Static Factory Method Detail" },
 				{ "tdoclet.File_error", "Error reading file: {0}" },
 				{ "tdoclet.Following_From_Class", "Following copied from class: {0}" },
 				{ "tdoclet.Following_From_Interface", "Following copied from interface: {0}" },
 				{ "tdoclet.Frame_Alert", "Frame Alert" },
 				{ "tdoclet.Frame_Output", "Frame Output" },
 				{ "tdoclet.Frame_Version", "Frame version" },
 				{ "tdoclet.Frame_Warning_Message", "This document is designed to be viewed using the frames feature. If you see this message, you are using a non-frame-capable web client." },
 				{ "tdoclet.Frames", "Frames" },
 				{ "tdoclet.Generated_Docs_Untitled", "Generated Documentation (Untitled)" },
 				{ "tdoclet.Groupname_already_used", "In -group option, groupname already used: {0}" },
 				{ "tdoclet.Help", "HAjuda" },
 				{ "tdoclet.Help_annotation_type_line_1", "Each annotation type has its own separate page with the following sections:" },
 				{ "tdoclet.Help_annotation_type_line_2", "Annotation Type declaration" },
 				{ "tdoclet.Help_annotation_type_line_3", "Annotation Type description" },
 				{ "tdoclet.Help_enum_line_1", "Each enum has its own separate page with the following sections:" },
 				{ "tdoclet.Help_enum_line_2", "Enum declaration" },
 				{ "tdoclet.Help_enum_line_3", "Enum description" },
 				{ "tdoclet.Help_line_1", "Como este documento da API está organizado" },
 				{ "tdoclet.Help_line_10", "Todas as classes implementadas conhecidas" },
 				{ "tdoclet.Help_line_11", "Declaração de classe/interface" },
 				{ "tdoclet.Help_line_12", "Descrição de classe/interface" },
 				{ "tdoclet.Help_line_13", "Each summary entry contains the first sentence from the detailed description for that item. The summary entries are alphabetical, while the detailed descriptions are in the order they appear in the source code. This preserves the logical groupings established by the programmer." },
 				{ "tdoclet.Help_line_14", "Uso" },
 				{ "tdoclet.Help_line_15", "Each documented package, class and interface has its own Use page.  This page describes what packages, classes, methods, constructors and fields use any part of the given class or package. Given a class or interface A, its Use page includes subclasses of A, fields declared as A, methods that return A, and methods and constructors with parameters of type A.  You can access this page by first going to the package, class or interface, then clicking on the \"Use\" link in the navigation bar." },
 				{ "tdoclet.Help_line_16", "Hierarquia de Classes" },
 				{ "tdoclet.Help_line_17_with_tree_link", "There is a {0} page for all packages, plus a hierarchy for each package. Each hierarchy page contains a list of classes and a list of interfaces. The classes are organized by inheritance structure starting with <code>java.lang.Object</code>. The interfaces do not inherit from <code>java.lang.Object</code>." },
 				{ "tdoclet.Help_line_18", "When viewing the Overview page, clicking on \"Tree\" displays the hierarchy for all packages." },
 				{ "tdoclet.Help_line_19", "When viewing a particular package, class or interface page, clicking \"Tree\" displays the hierarchy for only that package." },
 				{ "tdoclet.Help_line_2", "This API (Application Programming Interface) document has pages corresponding to the items in the navigation bar, described as follows." },
 				{ "tdoclet.Help_line_20_with_deprecated_api_link", "The {0} page lists all of the API that have been deprecated. A deprecated API is not recommended for use, generally due to improvements, and a replacement API is usually given. Deprecated APIs may be removed in future implementations." },
 				{ "tdoclet.Help_line_21", "Principal" },
 				{ "tdoclet.Help_line_22", "The {0} contains an alphabetic list of all classes, interfaces, constructors, methods, and fields." },
 				{ "tdoclet.Help_line_23", "Anterior/Próximo" },
 				{ "tdoclet.Help_line_24", "These links take you to the next or previous class, interface, package, or related page." },
 				{ "tdoclet.Help_line_25", "Frames/Sem Frames" },
 				{ "tdoclet.Help_line_26", "These links show and hide the HTML frames.  All pages are available with or without frames." },
 				{ "tdoclet.Help_line_27", "Each serializable or externalizable class has a description of its serialization fields and methods. This information is of interest to re-implementors, not to developers using the API. While there is no link in the navigation bar, you can get to this information by going to any serialized class and clicking \"Serialized Form\" in the \"See also\" section of the class description." },
 				{ "tdoclet.Help_line_28", "The <a href=\"constant-values.html\">Constant Field Values</a> page lists the static final fields and their values." },
 				{ "tdoclet.Help_line_29", "This help file applies to API documentation generated using the standard doclet." },
 				{ "tdoclet.Help_line_3", "The {0} page is the front page of this API document and provides a list of all packages with a summary for each.  This page can also contain an overall description of the set of packages." },
 				{ "tdoclet.Help_line_4", "Each package has a page that contains a list of its classes and interfaces, with a summary for each. This page can contain four categories:" },
 				{ "tdoclet.Help_line_5", "Classe/Interface" },
 				{ "tdoclet.Help_line_6", "Each class, interface, nested class and nested interface has its own separate page. Each of these pages has three sections consisting of a class/interface description, summary tables, and detailed member descriptions:" },
 				{ "tdoclet.Help_line_7", "Diagrama de herança de classe" },
 				{ "tdoclet.Help_line_8", "Subclasses diretas" },
 				{ "tdoclet.Help_line_9", "Todas as subinterfaces conhecidas" },
 				{ "tdoclet.Help_title", "Ajuda API" },
 				{ "tdoclet.Hide_Lists", "ESCONDER LISTAS" },
 				{ "tdoclet.Hierarchy_For_All_Packages", "Hierarquia para todos os pacotes" },
 				{ "tdoclet.Hierarchy_For_Package", "Hierarquia para o pacote {0}" },
 				{ "tdoclet.Href_Annotation_Title", "annotation in {0}" },
 				{ "tdoclet.Href_Class_Or_Interface_Title", "classe ou interface em {0}" },
 				{ "tdoclet.Href_Class_Title", "classe em {0}" },
 				{ "tdoclet.Href_Enum_Title", "enum em {0}" },
 				{ "tdoclet.Href_Interface_Title", "interface em {0}" },
 				{ "tdoclet.Href_Type_Param_Title", "Tipo de parâmetro em {0}" },
 				{ "tdoclet.Implementing_Classes", "Todas as classes implementadas conhecidas:" },
 				{ "tdoclet.Index", "Índice" },
 				{ "tdoclet.Index_of_Fields_and_Methods", "Índice dos campos e métodos" },
 				{ "tdoclet.Inherited_API_Summary", "Resumo da API herdada" },
 				{ "tdoclet.Interface_Hierarchy", "Hierarquia da interface" },
 				{ "tdoclet.Interfaces_Italic", "Interfaces (italic)" },
 				{ "tdoclet.Link_To", "Link para" },
 				{ "tdoclet.MEMBERS", "INTEGRANTES" },
 				{ "tdoclet.MalformedURL", "Malformed URL: {0}" },
 				{ "tdoclet.Method_in", "Método em {0}" },
 				{ "tdoclet.NONE", "Vazio" },
 				{ "tdoclet.NO_FRAMES", "SEM FRAMES" },
 				{ "tdoclet.Next", "Próximo" },
 				{ "tdoclet.Next_Class", "Próxima Classe" },
 				{ "tdoclet.Next_Letter", "Próxima Letra" },
 				{ "tdoclet.Next_Package", "Próximo Pacote" },
 				{ "tdoclet.No_Non_Deprecated_Classes_To_Document", "No non-deprecated classes found to document." },
 				{ "tdoclet.No_Package_Comment_File", "For Package {0} Package.Comment file not found" },
 				{ "tdoclet.No_Source_For_Class", "Source information for class {0} not available." },
 				{ "tdoclet.Non_Frame_Version", "Versão sem frames." },
 				{ "tdoclet.None", "Vazio" },
 				{ "tdoclet.Note_0_is_deprecated", "Note: {0} is deprecated." },
 				{ "tdoclet.Option", "Opção" },
 				{ "tdoclet.Or", "Ou" },
 				{ "tdoclet.Other_Packages", "Outros pacotes" },
 				{ "tdoclet.Overrides", "Métodos sobrescritos:" },
 				{ "tdoclet.Overview", "Visão Geral" },
 				{ "tdoclet.Overview-Member-Frame", "Overview Member Frame" },
 				{ "tdoclet.Package", "Pacote" },
 				{ "tdoclet.Package_Description", "Package {0} Description" },
 				{ "tdoclet.Package_Hierarchies", "Package Hierarchies:" },
 				{ "tdoclet.Prev", "ANTERIOR" },
 				{ "tdoclet.Prev_Class", "Classe anterior" },
 				{ "tdoclet.Prev_Letter", "Letra anterior" },
 				{ "tdoclet.Prev_Package", "Pacote anterior" },
 				{ "tdoclet.Same_package_name_used", "Package name format used twice: {0}" },
 				{ "tdoclet.Serialization.Excluded_Class", "Non-transient field {1} uses excluded class {0}." },
 				{ "tdoclet.Serialization.Nonexcluded_Class", "Non-transient field {1} uses hidden, non-included class {0}." },
 				{ "tdoclet.Show_Lists", "Exibir Listas" },
 				{ "tdoclet.Skip_navigation_links", "Pular links de navegação" },
 				{ "tdoclet.Source_Code", "Código fonte:" },
 				{ "tdoclet.Specified_By", "Especificado por:" },
 				{ "tdoclet.Standard_doclet_invoked", "Standard doclet invoked..." },
 				{ "tdoclet.Static_method_in", "Método estático em {0}" },
 				{ "tdoclet.Static_variable_in", "Variável estática em {0}" },
 				{ "tdoclet.Style_Headings", "Cabeçalhos" },
 				{ "tdoclet.Style_line_1", "Folha de estilo Javadoc" },
 				{ "tdoclet.Style_line_10", "Cores e fontes da barra de navegação" },
 				{ "tdoclet.Style_line_11", "Dark Blue" },
 				{ "tdoclet.Style_line_2", "Define colors, fonts and other style attributes here to override the defaults" },
 				{ "tdoclet.Style_line_3", "Page background color" },
 				{ "tdoclet.Style_line_4", "Table colors" },
 				{ "tdoclet.Style_line_5", "Dark mauve" },
 				{ "tdoclet.Style_line_6", "Light mauve" },
 				{ "tdoclet.Style_line_7", "White" },
 				{ "tdoclet.Style_line_8", "Font used in left-hand frame lists" },
 				{ "tdoclet.Style_line_9", "Example of smaller, sans-serif font in frames" },
 				{ "tdoclet.Subclasses", "Subclasses diretas conhecidas:" },
 				{ "tdoclet.Subinterfaces", "All Known Subinterfaces:" },
 				{ "tdoclet.Summary", "RESUMO:" },
 				{ "tdoclet.The", "O(A)" },
 				{ "tdoclet.Tree", "Hierarquia" },
 				{ "tdoclet.URL_error", "Error fetching URL: {0}" },
 				{ "tdoclet.Variable_in", "Variável em {0}" },
 				{ "tdoclet.Window_ClassUse_Header", "Usos de {0} {1}" },
 				{ "tdoclet.Window_Class_Hierarchy", "Hierarquia de classe" },
 				{ "tdoclet.Window_Deprecated_List", "Lista de Depreciados" },
 				{ "tdoclet.Window_Help_title", "Ajuda API" },
 				{ "tdoclet.Window_Overview", "Listagem da visão geral" },
 				{ "tdoclet.Window_Overview_Summary", "Visão Geral" },
 				{ "tdoclet.Window_Single_Index", "Índice" },
 				{ "tdoclet.Window_Split_Index", "{0}-Índice" },
 				{ "tdoclet.also", "igualmente" },
 				{ "tdoclet.build_version", "Standard Doclet version {0}" },
 				{ "tdoclet.in_class", "{0} na classe {1}" },
 				{ "tdoclet.in_interface", "{0} na interface {1}" },
 				{ "tdoclet.link_option_twice", "Extern URL link option (link or linkoffline) used twice." },
 				{ "tdoclet.navAnnotationTypeMember", "ELEMENTO" },
 				{ "tdoclet.navAnnotationTypeOptionalMember", "OPCIONAL" },
 				{ "tdoclet.navAnnotationTypeRequiredMember", "OBRIGATÓRIO" },
 				{ "tdoclet.navClassUse", "Uso" },
 				{ "tdoclet.navConstructor", "CONSTR" },
 				{ "tdoclet.navDeprecated", "Depreciados" },
 				{ "tdoclet.navEnum", "ENUM CONSTANTS" },
 				{ "tdoclet.navFactoryMethod", "FACTORY" },
 				{ "tdoclet.navField", "Campos" },
 				{ "tdoclet.navMethod", "Métodos" },
 				{ "tdoclet.navNested", "NESTED" },
 				{ "tdoclet.package", "pacote" },
 				{ "tdoclet.see.class_or_package_not_found", "Tag {0}: reference not found: {1}" },
 				{ "tdoclet.see.malformed_tag", "Tag {0}: Malformed: {1}" },
 				{ "tdoclet.throws", "lança" },
 				{ "tdoclet.usage", "Provided by Standard doclet:\n-d <directory>                    Destination directory for output files\n-use                              Create class and package usage pages\n-version                          Include @version paragraphs\n-author                           Include @author paragraphs\n-docfilessubdirs                  Recursively copy doc-file subdirectories\n-splitindex                       Split index into one file per letter\n-windowtitle <text>               Browser window title for the documenation\n-doctitle <html-code>             Include title for the overview page\n-header <html-code>               Include header text for each page\n-footer <html-code>               Include footer text for each page\n-top    <html-code>               Include top text for each page\n-bottom <html-code>               Include bottom text for each page\n-link <url>                       Create links to javadoc output at <url>\n-linkoffline <url> <url2>         Link to docs at <url> using package list at <url2>\n-excludedocfilessubdir <name1>:.. Exclude any doc-files subdirectories with given name.\n-group <name> <p1>:<p2>..         Group specified packages together in overview page\n-nocomment                        Supress description and tags, generate only declarations.\n-nodeprecated                     Do not include @deprecated information\n-noqualifier <name1>:<name2>:...  Exclude the list of qualifiers from the output.\n-nosince                          Do not include @since information\n-notimestamp                      Do not include hidden time stamp\n-nodeprecatedlist                 Do not generate deprecated list\n-notree                           Do not generate class hierarchy\n-noindex                          Do not generate index\n-nohelp                           Do not generate help link\n-nonavbar                         Do not generate navigation bar\n-serialwarn                       Generate warning about @serial tag\n-tag <name>:<locations>:<header>  Specify single argument custom tags\n-taglet                           The fully qualified name of Taglet to register\n-tagletpath                       The path to Taglets\n-charset <charset>                Charset for cross-platform viewing of generated documentation.\n-helpfile <file>                  Include file that help link links to\n-linksource                       Generate source in HTML\n-sourcetab <tab length>           Specify the number of spaces each tab takes up in the source\n-keywords                         Include HTML meta tags with package, class and member info\n-stylesheetfile <path>            File to change style of the generated documentation\n-docencoding <name>               Output encoding name" } };
   }
 }